In [17]:
import pandas as pd

In [18]:
df_ref = pd.read_csv(r"C:\Users\Admin\Desktop\CP\Data\processed\merged_df.csv")

In [19]:
df_ref

,ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,CP105,51.408820,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,39.300897,...,51.372876,45.154620,38.591292,32.102879,26.155350,21.227770,17.730555,15.902838,15.736829,16.955275
1,CP111,37.957060,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.665230,23.454627,...,54.336050,48.689244,42.710607,36.123512,29.556417,23.620913,18.962990,16.150704,15.001421,14.935191
2,CP113,34.543478,33.568140,32.195900,30.524125,28.655009,26.635878,24.472867,22.176569,19.786189,...,34.661066,28.846462,23.463793,18.915385,15.390320,12.947345,11.602520,11.357084,12.179563,13.968662
3,CP127,39.280994,37.954086,37.565979,37.898317,36.484441,34.009033,31.881341,29.772771,27.657092,...,38.296512,33.717704,28.803688,23.955544,19.446595,15.524868,12.601406,10.841740,10.075318,10.333831
4,CP157,34.197200,35.312177,36.060747,35.624389,34.566009,33.649150,32.641324,31.035173,28.675158,...,61.099208,57.061305,51.597262,44.833063,37.268508,29.703760,22.975866,17.964445,15.561585,16.119956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,CP152,42.429747,40.102682,36.755350,33.408856,30.922122,27.753506,24.640012,21.544426,18.561348,...,55.231592,53.383502,50.746365,47.185969,42.841141,37.997811,33.205888,28.943379,25.484040,22.766658
191,CP170,27.045223,26.060930,25.342578,24.680958,23.506208,21.747387,20.011563,18.636352,17.367513,...,55.361977,51.864558,47.604370,42.820967,37.690930,32.667078,28.316491,25.181901,23.573280,23.235346
192,CP195,43.094113,41.603654,40.014215,38.368341,36.680087,34.948594,33.165763,31.316489,29.379185,...,45.633593,41.745998,36.806451,31.039062,24.971145,19.298280,14.674303,11.439663,9.590914,9.137108
193,CP83,29.389849,28.819173,28.800633,28.806647,28.425304,27.505517,26.088310,24.249631,22.013928,...,42.732546,37.010111,31.439729,26.273291,21.687163,17.841182,14.871403,12.842567,11.731675,11.424054
194,CP98,37.960330,35.169578,32.530529,29.971407,27.427590,24.972638,22.804737,21.064037,19.682343,...,22.534464,21.843854,21.268819,20.114453,17.987087,14.978554,11.552470,8.262363,5.531289,3.551057

In [20]:
df_ref_avg = df_ref.drop("ID",axis=1)

In [21]:
avg_row = pd.DataFrame([df_ref_avg.mean()])

In [22]:
avg_row

,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,aSagH_18,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,40.3125,39.070938,37.869729,36.580787,35.131585,33.57956,31.948121,30.181892,28.254313,26.233156,...,52.741319,49.826592,46.32319,42.379689,38.194856,34.017633,30.217389,27.192137,25.255555,24.502785

In [23]:
avg_row.to_csv(r"C:\Users\Admin\Desktop\CP\Data\processed\avg_referenced.csv",index=False)