In [164]:
import pandas as pd

In [165]:
data = pd.read_csv(r'C:\Users\Admin\Desktop\CP\Data\processed\final_processed\GAIT_analysis_dataset.csv')

In [166]:
data_B = data[0:356]
data_B['Patient ID'] = data_B['Patient ID'].str.replace('^','DS_B_',regex=True)
data_B

C:\Users\Admin\AppData\Local\Temp\ipykernel_3876\3826796496.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_B['Patient ID'] = data_B['Patient ID'].str.replace('^','DS_B_',regex=True)

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,DS_B_1,34.489231,33.190099,31.611866,29.735892,27.653619,25.561388,23.659099,22.070589,20.809243,...,50.180644,48.361048,45.747773,42.545444,39.002017,35.373413,31.893023,28.766132,26.183560,24.284412
1,DS_B_2,34.115943,33.845007,33.142873,32.425595,31.833842,31.200395,30.316142,29.124648,27.683478,...,36.856681,41.823153,45.755571,47.958314,48.090432,46.405582,43.682483,40.756274,38.099251,35.805094
2,DS_B_3,46.266824,43.885923,41.490654,39.073092,36.650765,34.278363,32.022496,29.928085,27.998026,...,56.275353,53.910564,50.906875,47.310920,43.265528,39.025186,34.929357,31.336358,28.524134,26.583531
3,DS_B_4,31.919585,29.332622,26.944135,24.833541,23.089692,21.746950,20.720097,19.807280,18.798043,...,56.399781,54.999984,52.696951,49.514561,45.606221,41.252328,36.805056,32.613890,28.952887,25.959657
4,DS_B_5,34.398839,32.395244,30.418174,28.569600,26.850805,25.226143,23.697601,22.251928,20.845959,...,46.017507,42.047962,37.776869,33.473623,29.385098,25.673032,22.376516,19.419898,16.719602,14.333492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,DS_B_353,34.955706,33.189609,31.197574,28.906613,26.378893,23.701736,20.932425,18.124175,15.346144,...,59.748224,56.956329,53.057616,48.107750,42.352280,36.264038,30.480237,25.637320,22.183344,20.251466
352,DS_B_354,43.460763,41.366229,39.253434,37.186298,35.109748,32.733737,29.867751,26.645673,23.401994,...,66.245215,64.274939,61.447037,57.564585,52.582207,46.773671,40.750097,35.394397,31.520414,29.483590
353,DS_B_355,45.973445,45.436610,44.718654,43.733498,42.472684,41.031762,39.463440,37.731146,35.787922,...,51.425834,46.775414,41.665299,36.420451,31.372851,26.854424,23.175525,20.584527,19.217155,19.053352
354,DS_B_356,46.184037,44.926099,43.587212,41.911523,40.033367,38.343342,36.932185,35.532516,33.814459,...,53.595582,49.616682,44.797414,39.500984,34.108604,28.975083,24.389498,20.650562,18.174989,17.351090
355,DS_B_357,48.618641,46.854724,45.416792,43.861400,41.720761,39.180297,36.965007,35.353545,34.111946,...,55.364538,51.592765,47.073783,42.173804,37.171813,32.202162,27.488014,23.529098,20.986715,20.406589

In [167]:
data_A = data[356:712]
data_A['Patient ID'] = data_A['Patient ID'].str.replace('^CP','DS_A_',regex=True)
data_A

C:\Users\Admin\AppData\Local\Temp\ipykernel_3876\275179636.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_A['Patient ID'] = data_A['Patient ID'].str.replace('^CP','DS_A_',regex=True)

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
356,DS_A_105,51.408820,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,39.300897,...,51.372876,45.154620,38.591292,32.102879,26.155350,21.227770,17.730555,15.902838,15.736829,16.955275
357,DS_A_111,37.957060,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.665230,23.454627,...,54.336050,48.689244,42.710607,36.123512,29.556417,23.620913,18.962990,16.150704,15.001421,14.935191
358,DS_A_113,34.543478,33.568140,32.195900,30.524125,28.655009,26.635878,24.472867,22.176569,19.786189,...,34.661066,28.846462,23.463793,18.915385,15.390320,12.947345,11.602520,11.357084,12.179563,13.968662
359,DS_A_127,39.280994,37.954086,37.565979,37.898317,36.484441,34.009033,31.881341,29.772771,27.657092,...,38.296512,33.717704,28.803688,23.955544,19.446595,15.524868,12.601406,10.841740,10.075318,10.333831
360,DS_A_157,34.197200,35.312177,36.060747,35.624389,34.566009,33.649150,32.641324,31.035173,28.675158,...,61.099208,57.061305,51.597262,44.833063,37.268508,29.703760,22.975866,17.964445,15.561585,16.119956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,DS_A_152,42.429747,40.102682,36.755350,33.408856,30.922122,27.753506,24.640012,21.544426,18.561348,...,55.231592,53.383502,50.746365,47.185969,42.841141,37.997811,33.205888,28.943379,25.484040,22.766658
547,DS_A_170,27.045223,26.060930,25.342578,24.680958,23.506208,21.747387,20.011563,18.636352,17.367513,...,55.361977,51.864558,47.604370,42.820967,37.690930,32.667078,28.316491,25.181901,23.573280,23.235346
548,DS_A_195,43.094113,41.603654,40.014215,38.368341,36.680087,34.948594,33.165763,31.316489,29.379185,...,45.633593,41.745998,36.806451,31.039062,24.971145,19.298280,14.674303,11.439663,9.590914,9.137108
549,DS_A_83,29.389849,28.819173,28.800633,28.806647,28.425304,27.505517,26.088310,24.249631,22.013928,...,42.732546,37.010111,31.439729,26.273291,21.687163,17.841182,14.871403,12.842567,11.731675,11.424054
550,DS_A_98,37.960330,35.169578,32.530529,29.971407,27.427590,24.972638,22.804737,21.064037,19.682343,...,22.534464,21.843854,21.268819,20.114453,17.987087,14.978554,11.552470,8.262363,5.531289,3.551057

In [168]:
data_final = pd.concat([data_A, data_B], ignore_index=True)

In [169]:
data_final

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,DS_A_105,51.408820,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,39.300897,...,51.372876,45.154620,38.591292,32.102879,26.155350,21.227770,17.730555,15.902838,15.736829,16.955275
1,DS_A_111,37.957060,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.665230,23.454627,...,54.336050,48.689244,42.710607,36.123512,29.556417,23.620913,18.962990,16.150704,15.001421,14.935191
2,DS_A_113,34.543478,33.568140,32.195900,30.524125,28.655009,26.635878,24.472867,22.176569,19.786189,...,34.661066,28.846462,23.463793,18.915385,15.390320,12.947345,11.602520,11.357084,12.179563,13.968662
3,DS_A_127,39.280994,37.954086,37.565979,37.898317,36.484441,34.009033,31.881341,29.772771,27.657092,...,38.296512,33.717704,28.803688,23.955544,19.446595,15.524868,12.601406,10.841740,10.075318,10.333831
4,DS_A_157,34.197200,35.312177,36.060747,35.624389,34.566009,33.649150,32.641324,31.035173,28.675158,...,61.099208,57.061305,51.597262,44.833063,37.268508,29.703760,22.975866,17.964445,15.561585,16.119956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,DS_B_353,34.955706,33.189609,31.197574,28.906613,26.378893,23.701736,20.932425,18.124175,15.346144,...,59.748224,56.956329,53.057616,48.107750,42.352280,36.264038,30.480237,25.637320,22.183344,20.251466
547,DS_B_354,43.460763,41.366229,39.253434,37.186298,35.109748,32.733737,29.867751,26.645673,23.401994,...,66.245215,64.274939,61.447037,57.564585,52.582207,46.773671,40.750097,35.394397,31.520414,29.483590
548,DS_B_355,45.973445,45.436610,44.718654,43.733498,42.472684,41.031762,39.463440,37.731146,35.787922,...,51.425834,46.775414,41.665299,36.420451,31.372851,26.854424,23.175525,20.584527,19.217155,19.053352
549,DS_B_356,46.184037,44.926099,43.587212,41.911523,40.033367,38.343342,36.932185,35.532516,33.814459,...,53.595582,49.616682,44.797414,39.500984,34.108604,28.975083,24.389498,20.650562,18.174989,17.351090
550,DS_B_357,48.618641,46.854724,45.416792,43.861400,41.720761,39.180297,36.965007,35.353545,34.111946,...,55.364538,51.592765,47.073783,42.173804,37.171813,32.202162,27.488014,23.529098,20.986715,20.406589

In [170]:
data_C_hip = pd.read_excel(r'C:\Users\Admin\Desktop\CP\Data\raw\Dataset_C.xlsx',sheet_name='bCP_Hip_sagittal')

In [171]:
# Rename aSagH_pct_GC_{i} -> aSagH_{i/10}
import re

def rename_aSagH(col):
    match = re.match(r'aSagH_pct_GC_(\d+)', col)
    if match:
        num = int(match.group(1))
        return f'aSagH_{num//10}'
    return col

data_C_hip = data_C_hip.rename(columns=rename_aSagH)

In [172]:
# Keep only columns aSagH_i where i is even, plus 'Patient ID'
cols_to_keep = ['Patient ID'] + [
    x for x in data_C_hip.columns
    if re.match(r'aSagH_(\d+)$', x) and int(re.match(r'aSagH_(\d+)$', x).group(1)) % 2 == 0
]
data_C_hip = data_C_hip[cols_to_keep]

In [173]:
data_C_hip

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagH_82,aSagH_84,aSagH_86,aSagH_88,aSagH_90,aSagH_92,aSagH_94,aSagH_96,aSagH_98,aSagH_100
0,1,49.011606,46.346052,43.223755,39.128596,34.967296,32.120377,30.940064,29.764944,28.594098,...,46.937505,48.405140,49.515458,50.275080,50.713140,50.870668,50.782223,50.463972,49.919007,49.155811
1,2,37.711753,36.886777,36.359096,35.226970,33.456394,32.301829,30.565594,28.604849,26.484417,...,40.807227,42.349783,43.349942,43.517858,42.973091,41.824289,40.507305,39.478416,38.764516,38.041608
2,3,41.251698,40.716695,40.050459,39.238376,38.322901,37.367012,35.667308,34.022504,32.504784,...,40.887544,43.120005,44.554161,45.097623,44.828655,44.021709,43.023042,42.065537,41.169869,40.205868
3,4,38.828753,38.051785,36.969583,35.728100,34.586193,33.633997,32.636985,31.375533,29.653643,...,40.015887,41.551252,42.254427,42.191759,41.514129,40.438055,39.201164,38.004660,36.964386,36.088623
4,5,47.522390,47.700775,47.526272,46.520740,44.965820,43.393257,41.262371,38.845714,35.606450,...,48.269928,51.531763,54.020109,55.207822,54.945048,53.655178,51.881642,49.937007,48.156222,46.911690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,32.855656,25.776706,21.048323,16.980092,13.020896,9.282995,8.628784,8.089769,7.645671,...,27.467864,29.815674,31.935315,33.702551,35.017935,35.816486,36.070841,35.788183,35.008409,33.810174
196,197,33.757530,32.946891,31.197263,28.234688,25.554793,23.565407,21.809213,19.969684,18.171961,...,34.952061,36.162326,36.927345,37.451262,37.988692,37.863797,37.578468,37.194910,36.596012,35.471736
197,198,40.199846,39.054877,38.108376,37.285236,36.394409,35.219840,32.925919,29.951794,26.735274,...,35.830745,38.800530,41.238114,43.024742,44.071808,44.357101,43.936534,42.939311,41.552774,39.990831
198,199,35.157352,34.030926,32.989384,32.002093,30.987107,29.842260,28.576014,27.133843,25.577090,...,37.148070,38.047325,38.732311,39.147288,39.236084,38.947842,38.265166,37.250460,36.033579,34.739587
199,200,38.605093,32.793844,30.551363,26.145640,22.780641,19.311805,18.422468,17.487175,16.565746,...,43.621382,45.513315,46.683380,47.085017,46.745358,45.747693,44.204744,42.245265,40.018133,37.700862

In [174]:
data_C_knee = pd.read_excel(r'C:\Users\Admin\Desktop\CP\Data\raw\Dataset_C.xlsx',sheet_name='bCP_Knee_sagittal')

In [175]:
# Rename aSagH_pct_GC_{i} -> aSagH_{i/10}
import re

def rename_aSagK(col):
    match = re.match(r'aSagK_pct_GC_(\d+)', col)
    if match:
        num = int(match.group(1))
        return f'aSagK_{num//10}'
    return col

data_C_knee = data_C_knee.rename(columns=rename_aSagK)

In [176]:
# Keep only columns aSagH_i where i is even, plus 'Patient ID'
cols_to_keep = ['Patient ID'] + [
    x for x in data_C_knee.columns
    if re.match(r'aSagK_(\d+)$', x) and int(re.match(r'aSagK_(\d+)$', x).group(1)) % 2 == 0
]
data_C_knee = data_C_knee[cols_to_keep]

In [177]:
x = list(data_C_knee.columns)

In [178]:
data_C = pd.concat([data_C_hip, data_C_knee[x[1:]]], axis=1)
#data_C['Patient ID'] = data_C['Patient ID'].astype(str).str.replace('^','DS_C_',regex=True)
data_C

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,1,49.011606,46.346052,43.223755,39.128596,34.967296,32.120377,30.940064,29.764944,28.594098,...,65.913432,64.192943,61.657415,58.434391,54.818999,51.198561,47.927548,45.242013,43.247490,41.934875
1,2,37.711753,36.886777,36.359096,35.226970,33.456394,32.301829,30.565594,28.604849,26.484417,...,48.303331,41.607227,34.255229,26.164107,17.792717,10.176320,4.553254,2.074266,2.677677,5.088984
2,3,41.251698,40.716695,40.050459,39.238376,38.322901,37.367012,35.667308,34.022504,32.504784,...,51.819279,49.134455,45.659153,41.482961,36.907105,32.521366,29.051028,26.866321,25.756372,25.264707
3,4,38.828753,38.051785,36.969583,35.728100,34.586193,33.633997,32.636985,31.375533,29.653643,...,57.195075,52.814016,47.678968,42.113590,36.568679,31.542480,27.476620,24.671587,23.238603,23.073602
4,5,47.522390,47.700775,47.526272,46.520740,44.965820,43.393257,41.262371,38.845714,35.606450,...,56.765096,54.095162,50.900051,47.073794,42.846707,38.567536,34.627453,31.531880,29.830827,29.795929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,32.855656,25.776706,21.048323,16.980092,13.020896,9.282995,8.628784,8.089769,7.645671,...,53.057838,53.095395,52.417981,50.918437,48.609298,45.654016,42.309296,38.808862,35.305403,31.912809
196,197,33.757530,32.946891,31.197263,28.234688,25.554793,23.565407,21.809213,19.969684,18.171961,...,49.980463,45.440509,40.339506,35.039338,29.539100,23.925379,19.071521,15.345623,12.950566,11.134650
197,198,40.199846,39.054877,38.108376,37.285236,36.394409,35.219840,32.925919,29.951794,26.735274,...,51.327328,51.516324,50.228792,47.568760,43.799480,39.350357,34.778862,30.687225,27.624914,25.987364
198,199,35.157352,34.030926,32.989384,32.002093,30.987107,29.842260,28.576014,27.133843,25.577090,...,51.659606,47.581029,42.919378,37.922150,32.970439,28.489629,24.829189,22.190722,20.599801,19.896414
199,200,38.605093,32.793844,30.551363,26.145640,22.780641,19.311805,18.422468,17.487175,16.565746,...,58.467814,58.972206,58.584221,57.276956,55.148018,52.394312,49.276837,46.060330,42.935570,39.978391

In [179]:
data_C['Patient ID'] = data_C['Patient ID'].astype(str).str.replace('^','DS_C_',regex=True)

In [180]:
data_C

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,DS_C_1,49.011606,46.346052,43.223755,39.128596,34.967296,32.120377,30.940064,29.764944,28.594098,...,65.913432,64.192943,61.657415,58.434391,54.818999,51.198561,47.927548,45.242013,43.247490,41.934875
1,DS_C_2,37.711753,36.886777,36.359096,35.226970,33.456394,32.301829,30.565594,28.604849,26.484417,...,48.303331,41.607227,34.255229,26.164107,17.792717,10.176320,4.553254,2.074266,2.677677,5.088984
2,DS_C_3,41.251698,40.716695,40.050459,39.238376,38.322901,37.367012,35.667308,34.022504,32.504784,...,51.819279,49.134455,45.659153,41.482961,36.907105,32.521366,29.051028,26.866321,25.756372,25.264707
3,DS_C_4,38.828753,38.051785,36.969583,35.728100,34.586193,33.633997,32.636985,31.375533,29.653643,...,57.195075,52.814016,47.678968,42.113590,36.568679,31.542480,27.476620,24.671587,23.238603,23.073602
4,DS_C_5,47.522390,47.700775,47.526272,46.520740,44.965820,43.393257,41.262371,38.845714,35.606450,...,56.765096,54.095162,50.900051,47.073794,42.846707,38.567536,34.627453,31.531880,29.830827,29.795929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,DS_C_196,32.855656,25.776706,21.048323,16.980092,13.020896,9.282995,8.628784,8.089769,7.645671,...,53.057838,53.095395,52.417981,50.918437,48.609298,45.654016,42.309296,38.808862,35.305403,31.912809
196,DS_C_197,33.757530,32.946891,31.197263,28.234688,25.554793,23.565407,21.809213,19.969684,18.171961,...,49.980463,45.440509,40.339506,35.039338,29.539100,23.925379,19.071521,15.345623,12.950566,11.134650
197,DS_C_198,40.199846,39.054877,38.108376,37.285236,36.394409,35.219840,32.925919,29.951794,26.735274,...,51.327328,51.516324,50.228792,47.568760,43.799480,39.350357,34.778862,30.687225,27.624914,25.987364
198,DS_C_199,35.157352,34.030926,32.989384,32.002093,30.987107,29.842260,28.576014,27.133843,25.577090,...,51.659606,47.581029,42.919378,37.922150,32.970439,28.489629,24.829189,22.190722,20.599801,19.896414
199,DS_C_200,38.605093,32.793844,30.551363,26.145640,22.780641,19.311805,18.422468,17.487175,16.565746,...,58.467814,58.972206,58.584221,57.276956,55.148018,52.394312,49.276837,46.060330,42.935570,39.978391

In [181]:
data_D_hip = pd.read_excel(r"C:\Users\Admin\Desktop\CP\Data\raw\Dataset_D.xlsx",sheet_name='uCP_Hip_sagittal')
data_D_knee = pd.read_excel(r"C:\Users\Admin\Desktop\CP\Data\raw\Dataset_D.xlsx",sheet_name='uCP_Knee_sagittal')

In [182]:
data_D_hip = data_D_hip.rename(columns=rename_aSagH)
data_D_knee = data_D_knee.rename(columns=rename_aSagK)

In [183]:
data_D_hip

,Patient ID,aSagH_0,aSagH_1,aSagH_2,aSagH_3,aSagH_4,aSagH_5,aSagH_6,aSagH_7,aSagH_8,...,aSagH_91,aSagH_92,aSagH_93,aSagH_94,aSagH_95,aSagH_96,aSagH_97,aSagH_98,aSagH_99,aSagH_100
0,1,55.517725,54.917016,54.429888,54.244911,54.473509,54.926287,55.082485,54.629153,53.636320,...,53.010166,53.650757,54.298677,55.033583,55.740490,55.814631,55.801732,55.422672,54.694963,53.771139
1,2,48.868736,48.430772,47.917662,47.332051,46.676476,45.953370,45.165054,44.313698,43.401344,...,48.466311,48.766368,48.965356,49.063947,49.063370,48.965589,48.773406,48.490453,48.121176,47.670541
2,3,29.566189,28.865526,28.152332,27.431390,26.707463,25.985196,25.268962,24.562649,23.869539,...,34.875912,34.491116,34.010896,33.436709,32.767928,32.003136,31.141797,30.185904,29.140924,28.017266
3,4,36.461926,35.993587,35.501357,34.994033,34.479387,33.963832,33.452312,32.948198,32.453345,...,38.380376,38.380456,38.217497,37.917299,37.511459,37.034111,36.518603,35.994243,35.483812,35.001690
4,5,43.827578,43.057672,42.263502,41.457268,40.646505,39.832535,39.010421,38.170787,37.302955,...,47.419572,46.726489,45.953157,45.090832,44.138115,43.104550,42.011818,40.891440,39.779364,38.708212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,31.012758,30.750610,30.489488,30.226984,29.960665,29.687963,29.406627,29.114710,28.811238,...,35.102554,34.445562,33.811072,33.216923,32.673361,32.183812,31.745324,31.349163,30.981264,30.624412
163,164,40.993449,40.757546,40.389380,40.069015,39.648925,39.234200,38.751212,38.025580,37.009590,...,43.049896,42.607271,42.129728,41.719809,41.398520,41.204987,41.053880,40.954579,40.892990,40.840162
164,165,20.887456,20.297260,19.671651,19.011546,18.318401,17.594746,16.844711,16.074377,15.291666,...,27.077264,27.044329,26.938222,26.732890,26.406620,25.944380,25.338687,24.590597,23.712050,22.727563
165,166,32.837266,32.512438,32.394426,32.360462,32.237961,31.862726,31.148673,30.132081,28.982616,...,40.682831,40.226634,39.569758,38.629156,37.397597,35.976774,34.565195,33.387203,32.603334,32.240323
166,167,42.619142,41.821474,40.993004,40.145090,39.286921,38.425269,37.564724,36.707853,35.855597,...,43.207555,43.239947,43.159736,42.963430,42.652733,42.233694,41.715589,41.110021,40.430308,39.690881

In [184]:
cols_to_keep = ['Patient ID'] + [
    x for x in data_D_hip.columns
    if re.match(r'aSagH_(\d+)$', x) and int(re.match(r'aSagH_(\d+)$', x).group(1)) % 2 == 0
]
data_D_hip = data_D_hip[cols_to_keep]

In [185]:
cols_to_keep = [
    x for x in data_D_knee.columns
    if re.match(r'aSagK_(\d+)$', x) and int(re.match(r'aSagK_(\d+)$', x).group(1)) % 2 == 0
]
data_D_knee = data_D_knee[cols_to_keep]

In [186]:
data_D_hip

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagH_82,aSagH_84,aSagH_86,aSagH_88,aSagH_90,aSagH_92,aSagH_94,aSagH_96,aSagH_98,aSagH_100
0,1,55.517725,54.429888,54.473509,55.082485,53.636320,50.127535,47.026909,45.344138,44.046285,...,48.483702,49.676405,50.637373,51.605224,52.473433,53.650757,55.033583,55.814631,55.422672,53.771139
1,2,48.868736,47.917662,46.676476,45.165054,43.401344,41.401938,38.900355,36.185203,33.301791,...,41.120210,43.498216,45.438079,46.956805,48.064857,48.766368,49.063947,48.965589,48.490453,47.670541
2,3,29.566189,28.152332,26.707463,25.268962,23.869539,22.533026,20.644021,18.929252,17.359276,...,32.959035,34.328564,35.140756,35.400509,35.160790,34.491116,33.436709,32.003136,30.185904,28.017266
3,4,36.461926,35.501357,34.479387,33.452312,32.453345,31.493794,30.510933,29.589393,28.643698,...,30.633722,33.372976,35.627361,37.272074,38.199654,38.380456,37.917299,37.034111,35.994243,35.001690
4,5,43.827578,42.263502,40.646505,39.010421,37.302955,35.456528,33.383434,31.343567,29.493947,...,50.041553,50.299782,49.915166,49.112788,48.043560,46.726489,45.090832,43.104550,40.891440,38.708212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,31.012758,30.489488,29.960665,29.406627,28.811238,28.167355,26.862515,25.444343,23.877094,...,37.187284,37.839256,37.704527,36.932212,35.757054,34.445562,33.216923,32.183812,31.349163,30.624412
163,164,40.993449,40.389380,39.648925,38.751212,37.009590,34.929431,33.696487,33.353748,32.714896,...,41.535888,42.849612,43.674042,43.871696,43.472955,42.607271,41.719809,41.204987,40.954579,40.840162
164,165,20.887456,19.671651,18.318401,16.844711,15.291666,13.726765,11.991060,10.426842,9.052839,...,25.366408,26.191510,26.680685,26.938053,27.061370,27.044329,26.732890,25.944380,24.590597,22.727563
165,166,32.837266,32.394426,32.237961,31.148673,28.982616,27.076962,26.136772,25.892548,25.181799,...,41.776013,42.330022,42.241932,41.711082,41.042559,40.226634,38.629156,35.976774,33.387203,32.240323
166,167,42.619142,40.993004,39.286921,37.564724,35.855597,34.162242,32.395158,30.597253,28.732267,...,39.384677,40.680621,41.725394,42.535705,43.071137,43.239947,42.963430,42.233694,41.110021,39.690881

In [187]:
data_D_knee

,aSagK_0,aSagK_2,aSagK_4,aSagK_6,aSagK_8,aSagK_10,aSagK_12,aSagK_14,aSagK_16,aSagK_18,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,28.221865,28.361485,30.445622,34.163762,35.899476,34.198508,31.812416,31.166376,30.396610,29.312122,...,46.435908,42.575310,38.898970,35.993358,33.442755,31.866822,31.001399,29.863000,29.110665,28.800334
1,32.662708,32.252133,32.323455,32.613537,32.806745,32.594844,31.631471,29.762700,26.960566,23.359951,...,63.062288,60.376495,56.889702,52.778040,48.286519,43.728051,39.458235,35.827491,33.117355,31.474292
2,5.891849,5.009328,4.313182,3.787628,3.417890,3.185867,3.112643,3.193425,3.279496,3.266923,...,53.114958,47.719521,41.397824,34.479512,27.475268,20.953440,15.367051,10.958726,7.725123,5.469725
3,13.438470,13.323977,13.574715,13.922977,14.154369,14.148227,13.904740,13.246602,12.208045,10.882213,...,33.987143,32.582515,30.289102,26.965773,22.631989,17.622787,12.645679,8.645789,6.464868,6.456522
4,24.520707,24.365330,24.422961,24.572284,24.652078,24.503695,24.034124,23.344796,22.624195,21.864517,...,57.371652,50.985422,44.082250,37.386791,31.553046,26.985116,23.776720,21.754831,20.653115,20.306199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,18.226051,18.710087,19.304939,19.906065,20.430262,20.832245,21.260998,21.421790,21.285870,20.651875,...,57.721646,52.870670,46.778846,40.000741,33.289863,27.441837,23.089373,20.526996,19.646060,20.010183
163,22.790003,25.102103,26.946819,28.704076,28.579687,27.390388,27.655504,29.039130,29.573647,28.882007,...,47.276169,44.219407,40.725512,36.413834,31.563812,26.488436,22.229380,19.698101,19.337913,20.868087
164,0.394258,0.248287,0.018982,-0.415548,-1.101867,-2.001552,-3.189261,-4.366673,-5.412459,-6.292356,...,37.596017,32.702072,27.110246,21.200292,15.439498,10.258086,5.990952,2.765574,0.482009,-1.014051
165,19.123887,19.993055,21.197892,21.347156,19.797278,17.939133,17.728490,18.394241,18.009924,16.293715,...,60.415707,55.501876,49.256081,42.360675,35.737430,30.014115,25.111013,20.659160,17.507859,17.263962
166,13.708076,13.658834,14.072057,14.650487,15.129238,15.357732,15.294958,14.933602,14.303002,13.423468,...,46.593001,40.746181,34.907988,29.404830,24.433295,20.159706,16.748326,14.298623,12.821758,12.248274

In [188]:
data_D = pd.concat([data_D_hip, data_D_knee], axis=1)

data_D['Patient ID'] = data_D['Patient ID'].astype(str).str.replace('^','DS_D_',regex=True)
data_D

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,DS_D_1,55.517725,54.429888,54.473509,55.082485,53.636320,50.127535,47.026909,45.344138,44.046285,...,46.435908,42.575310,38.898970,35.993358,33.442755,31.866822,31.001399,29.863000,29.110665,28.800334
1,DS_D_2,48.868736,47.917662,46.676476,45.165054,43.401344,41.401938,38.900355,36.185203,33.301791,...,63.062288,60.376495,56.889702,52.778040,48.286519,43.728051,39.458235,35.827491,33.117355,31.474292
2,DS_D_3,29.566189,28.152332,26.707463,25.268962,23.869539,22.533026,20.644021,18.929252,17.359276,...,53.114958,47.719521,41.397824,34.479512,27.475268,20.953440,15.367051,10.958726,7.725123,5.469725
3,DS_D_4,36.461926,35.501357,34.479387,33.452312,32.453345,31.493794,30.510933,29.589393,28.643698,...,33.987143,32.582515,30.289102,26.965773,22.631989,17.622787,12.645679,8.645789,6.464868,6.456522
4,DS_D_5,43.827578,42.263502,40.646505,39.010421,37.302955,35.456528,33.383434,31.343567,29.493947,...,57.371652,50.985422,44.082250,37.386791,31.553046,26.985116,23.776720,21.754831,20.653115,20.306199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,DS_D_163,31.012758,30.489488,29.960665,29.406627,28.811238,28.167355,26.862515,25.444343,23.877094,...,57.721646,52.870670,46.778846,40.000741,33.289863,27.441837,23.089373,20.526996,19.646060,20.010183
163,DS_D_164,40.993449,40.389380,39.648925,38.751212,37.009590,34.929431,33.696487,33.353748,32.714896,...,47.276169,44.219407,40.725512,36.413834,31.563812,26.488436,22.229380,19.698101,19.337913,20.868087
164,DS_D_165,20.887456,19.671651,18.318401,16.844711,15.291666,13.726765,11.991060,10.426842,9.052839,...,37.596017,32.702072,27.110246,21.200292,15.439498,10.258086,5.990952,2.765574,0.482009,-1.014051
165,DS_D_166,32.837266,32.394426,32.237961,31.148673,28.982616,27.076962,26.136772,25.892548,25.181799,...,60.415707,55.501876,49.256081,42.360675,35.737430,30.014115,25.111013,20.659160,17.507859,17.263962
166,DS_D_167,42.619142,40.993004,39.286921,37.564724,35.855597,34.162242,32.395158,30.597253,28.732267,...,46.593001,40.746181,34.907988,29.404830,24.433295,20.159706,16.748326,14.298623,12.821758,12.248274

In [189]:
final_data = pd.concat([data_final, data_C, data_D], ignore_index=True)

In [190]:
final_data

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,DS_A_105,51.408820,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,39.300897,...,51.372876,45.154620,38.591292,32.102879,26.155350,21.227770,17.730555,15.902838,15.736829,16.955275
1,DS_A_111,37.957060,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.665230,23.454627,...,54.336050,48.689244,42.710607,36.123512,29.556417,23.620913,18.962990,16.150704,15.001421,14.935191
2,DS_A_113,34.543478,33.568140,32.195900,30.524125,28.655009,26.635878,24.472867,22.176569,19.786189,...,34.661066,28.846462,23.463793,18.915385,15.390320,12.947345,11.602520,11.357084,12.179563,13.968662
3,DS_A_127,39.280994,37.954086,37.565979,37.898317,36.484441,34.009033,31.881341,29.772771,27.657092,...,38.296512,33.717704,28.803688,23.955544,19.446595,15.524868,12.601406,10.841740,10.075318,10.333831
4,DS_A_157,34.197200,35.312177,36.060747,35.624389,34.566009,33.649150,32.641324,31.035173,28.675158,...,61.099208,57.061305,51.597262,44.833063,37.268508,29.703760,22.975866,17.964445,15.561585,16.119956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,DS_D_163,31.012758,30.489488,29.960665,29.406627,28.811238,28.167355,26.862515,25.444343,23.877094,...,57.721646,52.870670,46.778846,40.000741,33.289863,27.441837,23.089373,20.526996,19.646060,20.010183
914,DS_D_164,40.993449,40.389380,39.648925,38.751212,37.009590,34.929431,33.696487,33.353748,32.714896,...,47.276169,44.219407,40.725512,36.413834,31.563812,26.488436,22.229380,19.698101,19.337913,20.868087
915,DS_D_165,20.887456,19.671651,18.318401,16.844711,15.291666,13.726765,11.991060,10.426842,9.052839,...,37.596017,32.702072,27.110246,21.200292,15.439498,10.258086,5.990952,2.765574,0.482009,-1.014051
916,DS_D_166,32.837266,32.394426,32.237961,31.148673,28.982616,27.076962,26.136772,25.892548,25.181799,...,60.415707,55.501876,49.256081,42.360675,35.737430,30.014115,25.111013,20.659160,17.507859,17.263962
917,DS_D_167,42.619142,40.993004,39.286921,37.564724,35.855597,34.162242,32.395158,30.597253,28.732267,...,46.593001,40.746181,34.907988,29.404830,24.433295,20.159706,16.748326,14.298623,12.821758,12.248274

In [191]:
final_data.to_csv(r"C:\Users\Admin\Desktop\CP\Data\processed\final_processed\dataset_final.csv", index=False)

In [197]:
final_data

,Patient ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,DS_A_105,51.408820,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,39.300897,...,51.372876,45.154620,38.591292,32.102879,26.155350,21.227770,17.730555,15.902838,15.736829,16.955275
1,DS_A_111,37.957060,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.665230,23.454627,...,54.336050,48.689244,42.710607,36.123512,29.556417,23.620913,18.962990,16.150704,15.001421,14.935191
2,DS_A_113,34.543478,33.568140,32.195900,30.524125,28.655009,26.635878,24.472867,22.176569,19.786189,...,34.661066,28.846462,23.463793,18.915385,15.390320,12.947345,11.602520,11.357084,12.179563,13.968662
3,DS_A_127,39.280994,37.954086,37.565979,37.898317,36.484441,34.009033,31.881341,29.772771,27.657092,...,38.296512,33.717704,28.803688,23.955544,19.446595,15.524868,12.601406,10.841740,10.075318,10.333831
4,DS_A_157,34.197200,35.312177,36.060747,35.624389,34.566009,33.649150,32.641324,31.035173,28.675158,...,61.099208,57.061305,51.597262,44.833063,37.268508,29.703760,22.975866,17.964445,15.561585,16.119956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,DS_D_163,31.012758,30.489488,29.960665,29.406627,28.811238,28.167355,26.862515,25.444343,23.877094,...,57.721646,52.870670,46.778846,40.000741,33.289863,27.441837,23.089373,20.526996,19.646060,20.010183
914,DS_D_164,40.993449,40.389380,39.648925,38.751212,37.009590,34.929431,33.696487,33.353748,32.714896,...,47.276169,44.219407,40.725512,36.413834,31.563812,26.488436,22.229380,19.698101,19.337913,20.868087
915,DS_D_165,20.887456,19.671651,18.318401,16.844711,15.291666,13.726765,11.991060,10.426842,9.052839,...,37.596017,32.702072,27.110246,21.200292,15.439498,10.258086,5.990952,2.765574,0.482009,-1.014051
916,DS_D_166,32.837266,32.394426,32.237961,31.148673,28.982616,27.076962,26.136772,25.892548,25.181799,...,60.415707,55.501876,49.256081,42.360675,35.737430,30.014115,25.111013,20.659160,17.507859,17.263962
917,DS_D_167,42.619142,40.993004,39.286921,37.564724,35.855597,34.162242,32.395158,30.597253,28.732267,...,46.593001,40.746181,34.907988,29.404830,24.433295,20.159706,16.748326,14.298623,12.821758,12.248274

In [198]:
df = final_data.copy()

In [199]:
# Separate the columns
hip_cols = [col for col in df.columns if 'aSagH_' in col]
knee_cols = [col for col in df.columns if 'aSagK_' in col]

# Sanity check
print(len(hip_cols), len(knee_cols))  # Both should be 101

51 51

In [200]:
import numpy as np

# Stack along last dimension: shape (918, 101, 2)
hip_data = df[hip_cols].to_numpy()
knee_data = df[knee_cols].to_numpy()

# Combine hip and knee
data = np.stack([hip_data, knee_data], axis=-1)  # shape: (918, 101, 2)

In [201]:
from sklearn.preprocessing import MinMaxScaler

# Normalize each feature across the entire dataset
scalers = []
for i in range(data.shape[2]):
    scaler = MinMaxScaler()
    data[:, :, i] = scaler.fit_transform(data[:, :, i])
    scalers.append(scaler)

# Save for later
np.save("gait_data.npy", data)